modLoader="javafml" #mandatory
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="nomoremobspawning" #mandatory

version="1.16.5-1.0.1-beta" #mandatory
 # A display name for the mod
displayName="No More Mob Spawning" #mandatory

logoFile="logo.png" #optional

credits="Thanks to Wolfgang Hochleitner and Michael Lankes"
authors="Tobias Filler, Lukas Hartinger"
description='''
A small mod that provides the player with a way to prevent mobs from spawning, called the Anti-Mob Beacon. There is no more need to have builts light up in total or spawn strings to stop mobs from spawning, you can now have a dark area without worrying about mobs spawning. :3 '''

[[dependencies.nomoretorchspam]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"
[[dependencies.nomoretorchspam]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"
